[book]
authors = ["Parker Lamb"]
language = "en"
multilingual = false
src = "src"
title = "Projects"

[build]
build-dir = "../static/projects"

[output.html]
site-url = "/projects/"
no-section-label = true
mathjax-support = true
default-theme = "rust"
preferred-dark-theme = "rust"
git-repository-url = "/" # link to homepage
git-repository-icon = "fa-home"

[preprocessor.katex]
after = ["links"]
