# Site title
title = "Andromeda"
base_url = "https://www.andromeda.is"
description = "My site with all the things."
compile_sass = true
theme = "andromeda"

[extra]
header_links = [
    {name = "Projects", url="/projects/"},
    {name = "Photojournal", url = "/blog"},
    {name = "Quotes", url = "/quotes"}
]
license = "CC BY-NC 2.0"
favicon = "/images/favicon.ico"
email = "parker@plamb.com"
name = "Parker Lamb"
