# Site title
title = "Andromeda"
base_url = "https://blog.andromeda.is"
description = "Photography journal theme for Zola"
compile_sass = true
theme = "andromeda"

[extra]
header_links = [
    # {name = "Blog", url = "https://blog.andromeda.is/"}
]
license = "CC BY-NC 2.0"
favicon = "/images/favicon.ico"
email = "parker@plamb.com"
name = "Parker Lamb"