# Site title
title = "Andromeda"
base_url = "https://www.andromeda.is"
description = "My site with all the things."
compile_sass = true
theme = "andromeda"

[extra]
header_links = [
    {name = "Quotes", url = "/quotes"},
    {name = "Work", url = "/work"},
    {name = "Blog", url = "/blog"}
]
license = "CC BY-NC 2.0"
favicon = "/images/favicon.ico"
email = "parker@plamb.com"
name = "Parker Lamb"