# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install latest rust toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Install latest mdbook and katex
        run: |
          cargo install mdbook
          cargo install mdbook-katex
      - name: Build Book
        run: | 
          # This assumes your book is in the root of your repository.
          # Just add a `cd` here if you need to change to another directory.
          cd ship/
          mdbook build

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        with:
          fetch-depth: 0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          #TOKEN: ${{ secrets.GITHUB_TOKEN }}
